### ISSUE TITLE
FR: Support update domain

### ISSUE THREAD

**Issue by saya6k** [oukene/smartthings_customize#26]
In attributes and command, there are attributes and commands related to firmware.

Add support to update domain.

**Comment by oukene** [comment]
please more detail information

**Comment by saya6k** [comment]
I have an Air Purifier that includes various attributes and commands pertaining to software updates. Here are the relevant attributes:

- Version number (samsungce.driverVersion.versionNumber)
- Last updated date (samsungce.softwareUpdate.lastUpdatedDate)
- Availability of a new version (samsungce.softwareUpdate.newVersionAvailable)
- Operating state (samsungce.softwareUpdate.operatingState)
- OTnDUID (samsungce.softwareUpdate.otnDUID) - I don't know what it is though
- Update progress (samsungce.softwareUpdate.progress)
- Target module (samsungce.softwareUpdate.targetModule)

The available commands for the software updates are:

- Agree to update (samsungce.softwareUpdate.agreeUpdate)
- Disagree to update (samsungce.softwareUpdate.disagreeUpdate)
- 
I want to integrate these attributes and commands with the Home Assistant Update entity. The relevant Home Assistant attributes are:

Installed version (installed_version)
Latest version (latest_version)
Update in progress (in_progress)

With update domain entity, I can use the Home Assistant services `update.install`, `update.skip`, and `update.clear_skipped` for managing these updates.

With this feature, you will no longer need to use the SmartThings app to manage updates for your Air Purifier.

**Comment by oukene** [comment]
Added update entity to new branch.

However, I am not sure if 'agreeUpdate' will work properly. I don't know what the 'module' value used as an argument is.

There is a firmwareUpdate capability in the smartthings capability list, but it is not used in the Samsung home appliances I am using and is only added as a custom capability. (It also doesn't show the correct values.)


If the currentVersion and availableVersion values ​​of the attribute are valid, it seems possible to check whether an update exists.

**Comment by saya6k** [comment]
Works fine. Thanks
