### ISSUE TITLE
시하스 전력 미터기 전류 값 실시간 변경 안됨

### ISSUE THREAD

**Issue by heygoodluck** [oukene/smartthings_customize#29]
my.smartthings.com/advanced 에서는 전류 값이 지속적으로 반영되고 있는데 ha에서는 재시작을 했을 떄만 한번 반영되고 그 후에는 값이 동기화가 안돼요

**Comment by oukene** [comment]
마침 시하스 전력미터를 사용하고 있어서 확인해봤는데 잘 됩니다.
![전력미터](https://github.com/user-attachments/assets/5fd6b3ef-b28a-485e-90c7-28ffb6b26c7e)

위와 같은 증상은, capability 의 subscribe 처리 갯수를 넘어섰을 때 발생 하는데, (앱 당 이벤트 구독 제한 40개)
https://developer.smartthings.com/docs/getting-started/rate-limits

불 필요한 설정을 지우거나 ( 전력미터만 놔두고 설정 해보시거나 )

설정된 기기가 많지 않다면 완전 삭제 후 15분 이상 (넉넉히 30분 정도 후에) 지난 후에 다시 설정해서 사용해보세요


( 그런데 시하스 전력미터는 HA 에 로컬 연결을 지원하는데 굳이 스마트싱스를 통해서 연결할 필요가 있을까요..? )

**Comment by heygoodluck** [comment]
제가 zigbee 모델을 사용중이라..
전류 값이 아니였네요..
![image](https://github.com/user-attachments/assets/a3f44ebc-e12d-4f2f-a669-1584519cdbec)

**Comment by oukene** [comment]
wifi 모델에는 전류값은 없어서 그대로 테스트는 못해보겠네요

위에 말씀드린대로 테스트 할거 하나만 남기고 삭제 후 재설치 해서 확인해보세요

**Comment by heygoodluck** [comment]
넵

**Comment by heygoodluck** [comment]
다 삭제하고 해봤는데도 여전히 안되네요..ㅠㅠ

**Comment by oukene** [comment]
다른것들은 잘 되나요? 실시간 전력량 이라던지,,

**Comment by heygoodluck** [comment]
아뇨 다른것도 다 안돼요..

**Comment by oukene** [comment]
재현이 안되니 도움드릴 수 있을만한 방법이 마땅치 않네요, sensor 는 복잡하지도 않은데... 다른 디바이스도 그런가요?

**Comment by heygoodluck** [comment]
다른 디바이스는 정상적으로 작동하는데 시하스만 그러네요..ㅠㅠ

**Comment by oukene** [comment]
혹시 모르니 설정된 yaml 내용과, advance 사이트에서 보이는 attribute 항목 한번 볼려봐주실래요?

**Comment by heygoodluck** [comment]
`name: "SIHAS"
    sensor:
      - name: "전류"
        component: main
        capability: afterguide46998.currentMeasurement
        state:
          attribute: current
      - name: "온도"
        component: main
        capability: temperatureMeasurement
        state:
          attribute: temperature
      - name: "전압"
        component: main
        capability: voltageMeasurement
        state:
          attribute: voltage
      - name: "전원"
        component: main
        capability: powerMeter
        state:
          attribute: power
      - name: "총 누적 계량 데이터"
        component: main
        capability: energyMeter
        state:
          attribute: energy
      - name: "역률"
        component: main
        capability: afterguide46998.powerfactorMeasurement
        state:
          attribute: powerFactor
      - name: "주파수"
        component: main
        capability: afterguide46998.frequencyMeasurement
        state:
          attribute: frequency`

**Comment by heygoodluck** [comment]
name: "SIHAS"
    sensor:
      - name: "전류"
        component: main
        capability: afterguide46998.currentMeasurement
        state:
          attribute: current
      - name: "온도"
        component: main
        capability: temperatureMeasurement
        state:
          attribute: temperature
      - name: "전압"
        component: main
        capability: voltageMeasurement
        state:
          attribute: voltage
      - name: "전원"
        component: main
        capability: powerMeter
        state:
          attribute: power
      - name: "총 누적 계량 데이터"
        component: main
        capability: energyMeter
        state:
          attribute: energy
      - name: "역률"
        component: main
        capability: afterguide46998.powerfactorMeasurement
        state:
          attribute: powerFactor
      - name: "주파수"
        component: main
        capability: afterguide46998.frequencyMeasurement
        state:
          attribute: frequency

**Comment by heygoodluck** [comment]
![KakaoTalk_Photo_2024-10-21-14-12-57](https://github.com/user-attachments/assets/56ab225d-6a0e-4867-bacd-18f970fba74b)

**Comment by heygoodluck** [comment]
![KakaoTalk_Photo_2024-10-21-14-12-51](https://github.com/user-attachments/assets/401d6434-829d-4a3c-8ab3-cb5a31fd92f4)

**Comment by oukene** [comment]
컴포넌트의 디버그 로깅 활성화를 켠 다음 컴포넌트를 다시 읽어오기 한 다음 디버그 로깅 활성화를 다시 끈 후 다운로드 받아진 파일에서 "Synchronizing subscriptions" 로 시작하는 로그 한번 올려봐주세요

**Comment by heygoodluck** [comment]
2024-10-21 14:17:42.665 DEBUG (MainThread) [custom_components.smartthings_customize.smartapp] Synchronizing subscriptions for 10 capabilities under app '66db7b69-dabd-4323-9fe4-bcfbab2792a8': {None, 'musicahead43206.fanmodev2', 'relativeHumidityMeasurement', 'temperatureMeasurement', 'lock', 'battery', 'fanSpeed', 'fanOscillationMode', 'switch', 'healthCheck'}

**Comment by oukene** [comment]
이벤트 받을려는 capability 이름이 위 로그에 포함이 되어있어야 상태 변경을 받을 수 있는데 설정이 잘못된 느낌이 듭니다.

**Comment by heygoodluck** [comment]
음.. 혹시 해결 방법이 있을까요?

**Comment by oukene** [comment]
```
globals:
  ignore_capabilities:

devices:
  - device_id: input device id
    sensor:
      - name: "전류"
        component: main
        capability: afterguide46998.currentMeasurement
        state:
          attribute: current

ignore_platforms:
  - scene

default_entity_id_format: "st_custom_%{device_id}_%{component}_%{capability}_%{attribute}_%{command}_%{name}"

```

싹 지우고 이렇게만 넣고 Synchronizing subscriptions 로그에 포함되는지 확인해보세요, device_id 넣어주고요

**Comment by heygoodluck** [comment]
2024-10-21 19:57:18.281 DEBUG (MainThread) [custom_components.smartthings_customize.smartapp] Synchronizing subscriptions for 1 capabilities under app '66db7b69-dabd-4323-9fe4-bcfbab2792a8': {'afterguide46998.currentMeasurement'}

**Comment by heygoodluck** [comment]
해결됐네요~ 감사합니다!
